### ISSUE TITLE
TSR: Invalid elimination for an Object destructuring of an import case

### ISSUE THREAD

**Issue by SeanCassiere** [pcattori/babel-dead-code-elimination#9]
Part of https://github.com/TanStack/router/pull/1837, moving TanStack Router's plugins to use `babel-dead-code-elimination`.

- For reference, [this](https://github.com/TanStack/router/blob/main/packages/router-plugin/src/eliminateUnreferencedIdentifiers.ts) is our current dead code elimination process that currently works!
- For reference, [this](https://github.com/TanStack/router/blob/2d3b45b9b27484ae8092db5bd6c3a2443a939474/packages/router-plugin/src/compilers.ts#L29-L48) is how we are consuming the `babel-deal-code-elimination` package on our end

This is the test case that is failing.

Input:

```tsx
import thing from 'thing'

export function test() {
  const {
    foo: {
      bar: { destructured },
    },
  } = thing

  return destructured
}
```

Current output:

```tsx
export function test() {
  return destructured;
}
```

Expected output:

```tsx
import thing from 'thing';
export function test() {
  const {
    foo: {
      bar: {
        destructured
      }
    }
  } = thing;
  return destructured;
}
```

This is the [original test file](https://github.com/TanStack/router/blob/main/packages/router-plugin/tests/code-splitter/test-files/destructuring.tsx) should it prove useful.

**Comment by pcattori** [comment]
Fixed by #12
